### ISSUE TITLE
enhancement: stubs for resources

### ISSUE THREAD

**Issue by aioue** [gehadshaat/pyboto3#4]
Please add stubs for resources.

[Resources represent an object-oriented interface to Amazon Web Services (AWS). They provide a higher-level abstraction than the raw, low-level calls made by service clients.](https://boto3.readthedocs.io/en/latest/guide/resources.html)

```python
s3 = boto3.resource('s3')

for bucket in s3.buckets.all():
    print(bucket.name)
```

**Comment by gehadshaat** [comment]
this would be very useful. Currently the structure we are assuming is flat (just functions) and resources are not flat.

This will take sometime. I will look into it when I get the time. If anyone is interested in implementing this I will gladly help.
