### ISSUE TITLE
Tested on 3.7 unfortunately didn't work 

### ISSUE THREAD

**Issue by AJVA2580** [gehadshaat/pyboto3#7]
Hello, 

Thank you for trying to help the community.  I tried using it on Python 3.7 and it doesn't work. 

Hopefully will soon - keep the great work

**Comment by adamdavis40208** [comment]
Working for me in 3.7:

```
 …/code $ python --version                                                                                                                                  
Python 3.7.5

 …/code/ $ pip install pyboto3                                                                                                                                          
Collecting pyboto3
  Downloading https://files.pythonhosted.org/packages/4e/3a/09337861cbde049f8a69fd8f9ee9f9dd882c40b7e30e53e89560bc58975e/pyboto3-1.4.4.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 4.6MB/s
Installing collected packages: pyboto3
  Running setup.py install for pyboto3 ... done
Successfully installed pyboto3-1.4.4
```

![image](https://user-images.githubusercontent.com/19850646/78273773-2ae0a980-74c4-11ea-9818-af93c06c7333.png)

**Comment by gehadshaat** [comment]
@AJVA2580 What IDE are you using? This is has been tested on Pycharm. Make sure you have your type hint immediately after the line. It might not work for all IDEs.

**Comment by soyer-dev** [comment]
It doesn't work for ec2 for me, I see the autocomplete for ecs s3 etc but not ec2. Any idea ?
Using PyCharm and python 3.7
